load("@enc_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "block",
    srcs = [
        "__init__.py",
        "block.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "ghash",
    srcs = [
        "__init__.py",
        "ghash.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "ctr",
    srcs = [
        "__init__.py",
        "ctr.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":block",
        ":ghash",
        requirement("frx"),
        requirement("numpy"),
    ],
)

py_library(
    name = "gcm",
    srcs = [
        "__init__.py",
        "gcm.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":block",
        ":ctr",
        ":ghash",
        "//enc_frx:aead",
        requirement("frx"),
    ],
)
