load("@enc_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "ntt",
    srcs = [
        "__init__.py",
        "ntt.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ],
)
